# Generated by Django 5.2.4 on 2025-07-27 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.myimagemodel"
            ),
        ),
    ]
