# Generated by Django 5.2.4 on 2025-07-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myimagemodel",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
