# Generated by Django 5.2.4 on 2025-07-27 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_myimagemodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.myimagemodel"
            ),
        ),
    ]
