# Generated by Django 5.2.4 on 2025-07-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
        migrations.DeleteModel(
            name="MyImageModel",
        ),
    ]
